"""兼容旧导入路径；新代码使用 :mod:`app.ai.tools.fitness`。"""

from app.ai.tools.fitness import (
    ASSESS_RISK_TOOL,
    GENERATE_TRAINING_PLAN_TOOL,
    GET_LATEST_TRAINING_PLAN_TOOL,
    GET_PROFILE_TOOL,
    RECALL_USER_MEMORY_TOOL,
    RETRIEVE_FITNESS_KNOWLEDGE_TOOL,
    SAVE_TRAINING_PLAN_TOOL,
    VALIDATE_TRAINING_PLAN_TOOL,
    AssessRiskTool,
    GenerateTrainingPlanTool,
    GetLatestTrainingPlanTool,
    GetProfileTool,
    KnowledgeQuery,
    RecallUserMemoryTool,
    RetrieveFitnessKnowledgeTool,
    SaveTrainingPlanInput,
    SaveTrainingPlanTool,
    ValidateTrainingPlanTool,
    create_coach_tool_registry,
    create_training_plan_tool_registry,
)

__all__ = [
    "ASSESS_RISK_TOOL",
    "GENERATE_TRAINING_PLAN_TOOL",
    "GET_LATEST_TRAINING_PLAN_TOOL",
    "GET_PROFILE_TOOL",
    "RECALL_USER_MEMORY_TOOL",
    "RETRIEVE_FITNESS_KNOWLEDGE_TOOL",
    "SAVE_TRAINING_PLAN_TOOL",
    "VALIDATE_TRAINING_PLAN_TOOL",
    "AssessRiskTool",
    "GenerateTrainingPlanTool",
    "GetLatestTrainingPlanTool",
    "GetProfileTool",
    "KnowledgeQuery",
    "RecallUserMemoryTool",
    "RetrieveFitnessKnowledgeTool",
    "SaveTrainingPlanInput",
    "SaveTrainingPlanTool",
    "ValidateTrainingPlanTool",
    "create_coach_tool_registry",
    "create_training_plan_tool_registry",
]
